install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_extended_0.70.0_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.70.0_Linux-64bit.deb
script:
  - hugo

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: ${GH_TOKEN}
  keep-history: true
  on:
    branch: master