baseURL: https://docs.bestia-game.net
title: Bestia Game

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo: true

languageCode: en-us
contentDir: content
enableEmoji: true

module:
  imports:
    - path: github.com/colinwilson/lotusdocs
      disable: false
    - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5
      disable: false

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 3
  goldmark:
    renderer:
      unsafe: true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
    parser:
      attribute:
        block: true

